### PR TITLE
add rtl support

### LINKED ISSUE #29: PR - rtl support
I actually do this already in my project by setting `transform: 'translateX(180deg)'`. I can PR here it here as well :)

### PR DESCRIPTION
**Pull request by goldylucks**
resolves #29

Storybook screenshot:
image

### CODE REVIEW

**Comment by leMaik** [comment]
Great ~first~ second contribution, thank you so much for your PRs! :+1: I'll publish a new release when everything is done.

Looks like `rtl` should be handled by the theme instead of the prop, though? https://material-ui.com/guides/right-to-left/

You could just update the `styles` definition to take the `theme.direction` value into account.

**Comment by goldylucks** [comment]
you are correct sir!
updating now :)

I'm adding a short blob about it in readme as well, cool?

**Comment by leMaik** [comment]
@goldylucks Sounds good to me! Didn't know about how RTL support is done in Material-UI until yesterday either. A demo in the storybook that uses an RTL theme would be cool, too!

**Comment by goldylucks** [comment]
are you aware of any github badges for rtl support? I haven't found any. I'm adding to readme:

## Rtl support

Following MUi conventions, This package detects `rtl` from [`theme.direction`](https://material-ui.com/guides/right-to-left/), so rtl works out-of-the-box!

**Comment by goldylucks** [comment]
Much cleaner with using the theme, good call!

I've added a theme helper function to storybook. ATM rtl is hardcoded in, but it's very easy to abstract that away in the future if needed.

**Comment by leMaik** [comment]
I don't know a badge for rtl-support either. Tweaked the wording a bit.

Thanks again, your contributions are really appreciated! 🎉

**Pull request merged**
